name: test
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: "9.15.9"
      - uses: actions/setup-node@v4
        with:
          node-version: ">=22.16.0"
          cache: pnpm
      - uses: foundry-rs/foundry-toolchain@v1
      - run: echo ::add-matcher::.github/matcher.json

      - run: pnpm install --frozen-lockfile
      - run: pnpm test

      - uses: codecov/codecov-action@v4
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
