name: test
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: ">=9.10.0"
      - uses: actions/setup-node@v4
        with:
          node-version: ">=22.8.0"
          cache: pnpm
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-25f24e677a6a32a62512ad4f561995589ac2c7dc

      - run: pnpm install --frozen-lockfile

      - uses: codecov/codecov-action@v4
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
