name: version
on:
  push:
    branches: [main]
concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions:
  id-token: write
jobs:
  version:
    environment: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
      - uses: pnpm/action-setup@v4
        with:
          version: "9.15.9"
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: ">=22.16.0"
          cache: pnpm
      - uses: foundry-rs/foundry-toolchain@v1
      - run: pnpm install --frozen-lockfile
      - uses: crazy-max/ghaction-import-gpg@v5 # cspell:ignore ghaction
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true # cspell:ignore signingkey
          git_commit_gpgsign: true # cspell:ignore gpgsign
      - uses: changesets/action@v1
        with:
          title: 🔖 new release
          publish: pnpm changeset publish
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
